### ISSUE TITLE
Problem with get measures permission

### ISSUE THREAD

**Issue by jazeltq** [gnocchixyz/gnocchi#613] opened 2018-01-08 08:47 UTC
There is one policy in policy.json, here it is:
"metric_owner": "project_id:%(resource.project_id)s"

If one normal user (not admin) want to get measures from this metric, this policy in policy.json will raise an exception because it can not get project from resource.project_id....

**Comment by jd** [comment] 2018-01-08 09:14
Can you paste the backtrace you see?

**Comment by jazeltq** [comment] 2018-01-08 10:25
It raises 403.  We pdb into the gnocchi, and find this. It is a image. so I upload it here.
https://pasteboard.co/H1XsWVI.png

**Comment by jd** [comment] 2018-01-08 12:02
What version are you running?

It sounds like a duplicate of https://github.com/gnocchixyz/gnocchi/issues/464

**Comment by jazeltq** [comment] 2018-01-09 03:25
Oh, sounds like it. We use newton, it is 3.0.15...

**Closed** 2018-01-09 07:50 UTC
Labels: REST API
