### ISSUE TITLE
Redis incoming driver does not respect 'delay' parameter for processing.

### ISSUE THREAD

**Issue by atyronesmith** [gnocchixyz/gnocchi#507] opened 2017-11-22 15:47 UTC
### Which version of Gnocchi are you using
4.1

### How to reproduce your problem
The Redis incoming driver should respect the 'delay' processing setting.

### What is the result that you get
The incoming data in Redis is immediately processed even with a non-zero delay

### What is result that you expected
The incoming data would be processed after 'delay' seconds and with a period of 'delay' seconds like the other incoming drivers.

**Comment by chungg** [comment] 2017-11-22 16:56
:) i had same thoughts: #472

**Comment by jd** [comment] 2017-11-27 14:04
Note: #472 is a bit more "complex" as it'll improve the simple fix that is required to have this closed.

**Comment by jd** [comment] 2017-11-27 15:08
Closing as duplicate of #472 finally.

**Closed by jd** 2017-11-27 15:08 UTC
Labels: duplicate
