### ISSUE TITLE
error while inserting new errors into gnocchi

### ISSUE THREAD

**Issue by ramesh-chowdeshetty** [gnocchixyz/gnocchi#565] opened 2017-12-09 17:42 UTC
2017-12-09 17:41:50,599 [9496] ERROR    gnocchi.storage._carbonara: Error processing new measures
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gnocchi/storage/_carbonara.py", line 383, in process_new_measure
s
    self._compute_and_store_timeseries(metric, measures)
  File "/usr/local/lib/python2.7/dist-packages/gnocchi/storage/_carbonara.py", line 454, in _compute_and_store_
timeseries
    before_truncate_callback=_map_add_measures)
  File "/usr/local/lib/python2.7/dist-packages/gnocchi/carbonara.py", line 286, in set_values
    before_truncate_callback(self)
  File "/usr/local/lib/python2.7/dist-packages/gnocchi/storage/_carbonara.py", line 438, in _map_add_measures
    new_first_block_timestamp = bound_timeserie.first_block_timestamp()
  File "/usr/local/lib/python2.7/dist-packages/gnocchi/carbonara.py", line 382, in first_block_timestamp
    return rounded - (self.block_size * self.back_window)
  File "/usr/local/lib/python2.7/dist-packages/pandas/tseries/offsets.py", line 409, in __rsub__
    **self.kwds) + other
  File "/usr/local/lib/python2.7/dist-packages/pandas/tseries/offsets.py", line 2716, in __add__
    "will overflow".format(self, other))
OverflowError: the add operation between <-864000000000000000000 * Nanos> and 2017-09-18 00:00:00 will overflow

**Comment by sileht** [comment] 2017-12-09 19:33
Can you provide all asked information in the issue template ?

### Which version of Gnocchi are you using

### How to reproduce your problem

### What is the result that you get

### What is result that you expected

**Comment by sileht** [comment] 2017-12-09 19:34
At first glance, this error cannot occurs anymore, since Gnocchi does not use pandas anymore. Can you retry with the latest version ?

**Comment by sileht** [comment] 2017-12-12 11:58
This can't happen on a recent version, so I close the issue. Fill free to reopen it with more detail, if you can reproduce it with the latest version of Gnocchi.

**Closed by sileht** 2017-12-12 11:58 UTC
